version: '3'
networks:
  sitebasenet:

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/passwd:/etc/passwd
      - ./php-fpm/group:/etc/group
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ..:/var/www/html
    networks:
      - sitebasenet
  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=sitebase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./database/docker.cnf:/etc/mysql/conf.d/docker.cnf:ro
      - ./database/data:/var/lib/mysql
      - ..:/var/www/html
    networks:
      - sitebasenet
    env_file:
      - ../.env
    ports:
      - "3306:3306"
  elasticsearch:
    image: blacktop/elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - sitebasenet
  web:
    build:
      context: ./nginx
    volumes:
      - ..:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/passwd:/etc/passwd
      - ./nginx/group:/etc/group
    depends_on:
      - php-fpm
      - database
      - elasticsearch
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sitebasenet
    environment:
      SITEHOST: local.sitebase