networks:
  sitebasenet:
    driver: bridge
    ipam:
      config:
        - subnet: ${IPV4_CLASS}.0.0/16
#          gateway: ${IPV4_CLASS}.0.254

services:
  php-fpm:
    user: "${UID}:${GID}"
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ..:/var/www/html
    networks:
      sitebasenet:
        ipv4_address: ${IPV4_CLASS}.0.2
    depends_on:
      - database
      - elasticsearch
      - mailhog
      - redis
#    ports:
#      - 9003:9003
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  database:
    build:
      context: ./database
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./database/docker.cnf:/etc/mysql/conf.d/docker.cnf:ro
      - ./data/database/mysql:/var/lib/mysql
      - ..:/var/www/html
    networks:
      sitebasenet:
        ipv4_address: ${IPV4_CLASS}.0.3
    env_file:
      - ./.env
    ports:
      - 3306:3306
    restart: unless-stopped
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      sitebasenet:
        ipv4_address: ${IPV4_CLASS}.0.4
    restart: unless-stopped
  elasticsearch:
    image: blacktop/elasticsearch
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      sitebasenet:
        ipv4_address: ${IPV4_CLASS}.0.5
    restart: unless-stopped
  supervisor:
    user: "${UID}:${GID}"
    build:
      context: ./supervisor
    volumes:
      - ./supervisor/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./supervisor/supervisord.conf:/etc/supervisord.conf
      - ..:/var/www/html
    networks:
      sitebasenet:
        ipv4_address: ${IPV4_CLASS}.0.8
    depends_on:
      - php-fpm
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - 9001:9001 # supervisor
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      sitebasenet:
        ipv4_address: ${IPV4_CLASS}.0.6
    restart: unless-stopped
  web:
    build:
      context: ./nginx
    volumes:
      - ..:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    networks:
      sitebasenet:
        ipv4_address: ${IPV4_CLASS}.0.7
    env_file:
      - ./.env
    restart: unless-stopped
